### ISSUE TITLE
Error with require() of ES Module

### ISSUE THREAD

**Issue by BarraR3port** [Hacksore/react-skinview3d#27]
I'm getting this error when reloading my page.

I'm running this on Windows 11, node v18.12.0, Nextron(Electron + NextJS) 20.1.0 and TypeScript 4.8.2.

Everything works well, but when I reload the page/view, it crashes and shows this error in the console.

<details>
<summary>Error Log</summary>

```console
Instead change the require of skinview3d.js in C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\react-skinview3d\dist\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\react-skinview3d\dist\index.js:1:39)
    at react-skinview3d (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\pages\skins.js:62:18)
    at __webpack_require__ (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/skins/index.tsx:14:74)
    at __webpack_require__.a (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/skins/index.tsx:1:21)
    at ./pages/skins/index.tsx (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\pages\skins.js:22:1)
    at __webpack_require__ (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\webpack-runtime.js:33:42)
    at __webpack_exec__ (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\pages\skins.js:102:39)
    at C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\pages\skins.js:103:28
    at Object.<anonymous> (C:\Users\barra\WebstormProjects\PodPack-Electron\renderer\.next\server\pages\skins.js:106:3)
    at Object.requirePage (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\require.js:58:12)
    at C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\load-components.js:61:73
    at async Object.loadComponents (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\load-components.js:61:26)
    at async DevServer.findPageComponents (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\next-server.js:555:36)
    at async DevServer.renderPageComponent (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\base-server.js:891:24)
    at async DevServer.renderToResponse (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\base-server.js:920:32)
    at async DevServer.pipe (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\base-server.js:369:25)
    at async Object.fn (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\next-server.js:743:21)
    at async Router.execute (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\router.js:247:36)
    at async DevServer.run (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\base-server.js:347:29)
    at async DevServer.run (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\dev\next-dev-server.js:709:20)
    at async DevServer.handleRequest (C:\Users\barra\WebstormProjects\PodPack-Electron\node_modules\next\dist\server\base-server.js:285:20) {
  code: 'ERR_REQUIRE_ESM',
  page: '/skins'
}
```

</details>

**Comment by Hacksore** [comment]
Since this library doesn't work as a server component you'll need to import it differently.

https://codesandbox.io/s/react-skinview3d-next-esm-7n2eh1?file=/pages/index.js:0-36

previous issue https://github.com/Hacksore/react-skinview3d/issues/18

**Comment by BarraR3port** [comment]
This https://github.com/Hacksore/react-skinview3d/issues/18#issuecomment-1154653791 fixed the issue!
